### ISSUE TITLE
Compilazione singole sezioni non funzionante

### ISSUE THREAD

**Issue by MickPerl** [TommasoAzz/plain-x-project-management-report#11]
Sembrerebbe che, nonostante il comando `\documentclass[../../main.tex]{subfiles}`, non vengano richiamate tutte i pacchetti e i comandi inseriti in _style.sty_, tantochè quando vado a fare il build da _chapters/studio-fattibilita/studio-fattibilita.tex_, mi dice che non trova le immagini ad esempio (causa: non legge il comando `\graphicspath{{assets/images/}}` in `style.sty)`

**Comment by TommasoAzz** [comment]
@MickPerl chiudo perché risolto
