### ISSUE TITLE
Correzione parte di @MickPerl

### ISSUE THREAD

**Issue by TommasoAzz** [TommasoAzz/plain-x-project-management-report#12]
Relativa alla correzione di capitolo §3.

**Comment by TommasoAzz** [comment]
In Scenario 3 ancora parliamo di "dati anagrafici (età, genere, impiego, malattie pregresse)". Che fare?

**Comment by TommasoAzz** [comment]
Per Roberto, in §3.3.2 rimuoverei gli obiettivi "possibilità di esportare elementi grafici in formato immagine o widget HTML da incorporare", "possibilità di selezionare solo alcuni elementi grafici per comporli in una mini dashboard daincorporare" se è poi obbligatorio progettarli (diventerebbe troppo oneroso). Se invece si possono lasciare lì senza progettarli allora ben venga.

**Comment by TommasoAzz** [comment]
@MickPerl tutto tuo da verificare se ti va bene ciò che ho cambiato.

**Comment by MickPerl** [comment]
> In Scenario 3 ancora parliamo di "dati anagrafici (età, genere, impiego, malattie pregresse)". Che fare?

@TommasoAzz Lasciamo solo "età, genere"?

**Comment by MickPerl** [comment]
> @MickPerl tutto tuo da verificare se ti va bene ciò che ho cambiato.

Alla grande, buon lavoro @TommasoAzz !

**Comment by TommasoAzz** [comment]
> > In Scenario 3 ancora parliamo di "dati anagrafici (età, genere, impiego, malattie pregresse)". Che fare?
> 
> @TommasoAzz Lasciamo solo "età, genere"?

Forse sì? @jjocram ?

**Comment by jjocram** [comment]
Se non intendiamo prevedere la possibilità di accedere agli altri dati in quanto non sappiamo da dove andrebbero presi allora lasciamo solo età e genere
