### ISSUE TITLE
Colore più blando nelle iterazioni

### ISSUE THREAD

**Issue by TommasoAzz** [TommasoAzz/plain-x-project-management-report#19]
Riesci @MickPerl a mettere un blu/azzurro più tenue sia nel bordo che nel background del box di iterazioni? E' tanto forte questo.

![image](https://user-images.githubusercontent.com/16544602/108601646-e3922e80-739d-11eb-8118-6df1923c0161.png)

**Comment by MickPerl** [comment]
Provvedo
