### ISSUE TITLE
Immagini laterali in descrizione Persona

### ISSUE THREAD

**Issue by TommasoAzz** [TommasoAzz/plain-x-project-management-report#20]
Se viene modificato il contenuto e questa situazione in cui c'è spazio prima e dopo la foto si ripercuote nel passaggio da una pagina all'altra diventa molto fastidioso. Quindi dare più spazio lateralmente a mio avviso e meno in altezza (ovvero dar solo lo stretto spazio necessario).

![image](https://user-images.githubusercontent.com/16544602/108601699-2227e900-739e-11eb-9b97-b0d73adf71b3.png)

**Comment by MickPerl** [comment]
@TommasoAzz Risolto: da un'occhiata se va meglio.
