### ISSUE TITLE
Assenza link tra numeri di guidelines violate a loro definizione

### ISSUE THREAD

**Issue by MickPerl** [TommasoAzz/plain-x-project-management-report#6]
Mi riferisco alla sezione di "Analisi diretta": secondo me, potresti aggiungere un riferimento tra il numero della linea guida violata e l'item in cui è stata definita nella sezione "Linee guida"; anche per favorire consistenza ad altre parti del documento in cui questi tipi di riferimenti sono stati esplicitati.

- [x] aggiunta cross-reference link tra "Analisi diretta" e "Linee Guida";
- [x] aggiunta cross-reference link tra "Analisi indiretta" e "Linee Guida";

**Comment by jjocram** [comment]
Va bene, in giornata provvedo a risolvere

**Comment by jjocram** [comment]
Per quanto riguarda la reference tra Analisi indiretta e Linee Guida? Essendo riportate 1:1 è necessario referenziarne ognuna?

**Comment by MickPerl** [comment]
Puoi anche referenziare solo in corrispondenza delle violazioni o non mettere nessun riferimento: a tua discrezione.
